---
- name: Copy the gen folder of certificate server
  copy: src={{local_gen}}/{{cfg_loc}}/cs{{isd}}-{{as}}-{{cs}}
        dest={{repo_loc}}/gens/{{ts}}/{{cfg_loc}}
  remote_user: scion
  become: "{{simple_conf|default(false)}}"
  become_user: scion

- name: Add certificate service to the supervisord.conf file
  replace: dest={{repo_loc}}/gens/{{ts}}/{{cfg_loc}}/supervisord.conf
           regexp='(\s+programs.*)$'
           replace='\1,cs{{isd}}-{{as}}-{{cs}}'
