---
- hosts: scion_nodes
  tasks:
  - set_fact:
      cfg_loc: ISD{{isd}}/AS{{as}}
      repo_loc: /home/scion/go/src/github.com/scionproto/scion
      ts: "{{ lookup('pipe', 'stat --printf=%Y {{inventory_file}}') }}"

- hosts: scion_nodes
  roles:
    - copy_gen

- hosts: beacon_servers
  roles:
    - beacon_server

- hosts: path_servers
  roles:
    - path_server

- hosts: cert_servers
  roles:
    - cert_server

- hosts: border_routers
  roles:
    - border_router

- hosts: sibra_servers
  roles:
    - sibra_server

- hosts: zookeepers
  roles:
    - zk

# When all the above steps succeed, finally start the
# infrastructure on all the machines of this AS.
- hosts: scion_nodes
  tasks:
    - name: Switch-over to the new gen folder
      file: src={{repo_loc}}/gens/{{ts}}
            dest={{repo_loc}}/gen
            state=link
  remote_user: scion
  become: "{{simple_conf|default(false)}}"
  become_user: scion
