- hosts: zookeepers
  vars:
    repo_loc: /home/scion/go/src/github.com/scionproto/scion
  tasks:
    - name: Delete Zookeeper State
      command: tools/zkcleanslate
               chdir={{repo_loc}}
      environment:
        PYTHONPATH: "{{repo_loc}}"
  remote_user: scion
