---
- name: Copy the gen folder of path server
  copy: src={{local_gen}}/{{cfg_loc}}/ps{{isd}}-{{as}}-{{ps}}
        dest={{repo_loc}}/gens/{{ts}}/{{cfg_loc}}
  remote_user: scion
  become: "{{simple_conf|default(false)}}"
  become_user: scion

- name: Add path service to the supervisord.conf file
  replace: dest={{repo_loc}}/gens/{{ts}}/{{cfg_loc}}/supervisord.conf
           regexp='(\s+programs.*)$'
           replace='\1,ps{{isd}}-{{as}}-{{ps}}'
